# version: '3.9'

# services:
#   go-server:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3088:3088" 
#     environment:
#       - Secretkey=O4fsRj8iiSMlqjKduk94Uwm7dz3CEmk3scZqRi5K2vHRRr8m9SXDSdmr4IfcIhwT
#       - Port=3088

#   hasura:
#     image: hasura/graphql-engine:v2.35.0
#     ports:
#       - "9702:8080"
#     environment:
#       HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:password@host.docker.internal:5432/techubdb
#       HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
#       HASURA_GRAPHQL_ADMIN_SECRET: catcatsecret3
#     extra_hosts:
#       - "host.docker.internal:host-gateway"




















version: '3.9'

services:




  hasura:
    image: hasura/graphql-engine:v2.35.0
    ports:
      - "9702:8080"
 
    extra_hosts:
        - "localhost:host-gateway"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:password@localhost:5432/techubdb
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: catcatsecret3

volumes:
  postgres_data:





  

